### ISSUE TITLE
Allow specific IP only to specific port.

### ISSUE THREAD

**Issue by mxxcon** [jlund/ansible-ufw#1]
There are situations where I want to allow certain IPs only to certain ports, not all of them.

Also distinction between TCP and UDP would be nice.
Essentially:

```
ufw allow proto udp from 1.2.3.5 port 5469 to 1.2.3.4 port 5469
```

(or a wildcard from any appropriate field)

**Comment by jlund** [comment]
OK, this should be taken care of now as well!
