### ISSUE TITLE
Add support for `ufw limit`

### ISSUE THREAD

**Issue by mxxcon** [jlund/ansible-ufw#2]
I'm quoting ufw's man page:
ufw supports connection rate limiting, which is useful  for  protecting against brute-force login attacks. ufw will deny connections if an IP address has attempted to initiate 6 or more connections in the last 30 seconds. See http://www.debian-administration.org/articles/187 for details. Typical usage is:

```
ufw limit ssh/tcp
```

**Comment by jlund** [comment]
Done! Let me know what you think.

**Comment by mxxcon** [comment]
:+1: 
Maybe also somehow allow different limits on per-port basis? For example I might want to have higher throttle for ssh port but be more open with dns.

**Comment by jlund** [comment]
I agree that would be cool, but it doesn't look like ufw itself supports controlling the limit thresholds on a per-port basis. I could easily change these values in the generated template (and iptables would handle it just fine) however I don't think that deviating from core ufw functionality is a good idea for two reasons:
1. This is a ufw role, and I have spent a fair amount of time testing its output to make sure it matches ufw's exactly [1] [2] [3]
2. The purpose of ufw is to keep things simple

If I am somehow mistaken and there is a way to tell ufw to do this, please let me know and I'll take a look!

I am working on your other issue now.

[1] https://github.com/jlund/ansible-ufw/commit/84bfa4c392ad7f02dece7726278c663560ead76d
[2] https://github.com/jlund/ansible-ufw/commit/058213abbc2c4853c3e593fbffb8aa7b2252af5f
[3] https://github.com/jlund/ansible-ufw/commit/cd6c6edc2aa5f02ce05a23457df7a1bca0a36ce8

**Comment by mxxcon** [comment]
You are right. Strictly replicating ufw's command line functionality does not allow changing these limits.
I guess for that next logical step would be a full Ansible ufw module. :)
Thank you for adding the current implementation.

**Comment by jlund** [comment]
You are very welcome. Thank you for your suggestions!
